In [26]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

In [27]:
df=pd.read_csv('weatherAUS.csv')

In [28]:
df['RainToday'].unique()

<StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str

In [29]:
df.head(n=5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  str
 1   Location       145460 non-null  str
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  str
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  str
 10  WindDir3pm     141232 non-null  str
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  str
 22  RainTomorrow   142193 non-null  str
dtypes: float64(16), str(7)
memory usage: 25.5 MB

In [31]:
df=df.dropna(subset='RainToday')

In [32]:
df=df.drop(columns='RainTomorrow')

In [33]:
df['Date']=pd.to_datetime(df['Date'])

In [34]:
df['Date']=df['Date'].astype(int)

In [35]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,1228089600000000,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,24.0,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No
1,1228176000000000,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,22.0,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No
2,1228262400000000,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
3,1228348800000000,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
4,1228435200000000,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No

In [ ]:
df['Evaporation']=df['Evaporation'].fillna(df['Evaporation'].median())
df['Rainfall']=df['Rainfall'].fillna(df['Rainfall'].median())
df['MinTemp']=df['MinTemp'].fillna(df['MinTemp'].mean())
df['MaxTemp']=df['MaxTemp'].fillna(df['MaxTemp'].mean())
df['Sunshine']=df['Sunshine'].fillna(df['Sunshine'].mean())
df['WindGustDir']=df['WindGustDir'].fillna(df['WindGustDir'].mode()[0])
df['WindGustSpeed']=df['WindGustSpeed'].fillna(df['WindGustSpeed'].median())
df['WindDir9am']=df['WindDir9am'].fillna(df['WindDir9am'].mode()[0])
df['WindDir3pm']=df['WindDir3pm'].fillna(df['WindDir3pm'].mode()[0])
df['WindSpeed9am']=df['WindSpeed9am'].fillna(df['WindSpeed9am'].median())
df['WindSpeed3pm']=df['WindSpeed3pm'].fillna(df['WindSpeed3pm'].median())
df['Humidity9am']=df['Humidity9am'].fillna(df['Humidity9am'].median())
df['Humidity3pm']=df['Humidity3pm'].fillna(df['Humidity3pm'].median())
df['Pressure9am']=df['Pressure9am'].fillna(df['Pressure9am'].median())
df['Pressure3pm']=df['Pressure3pm'].fillna(df['Pressure3pm'].median())
df['Cloud9am']=df['Cloud9am'].fillna(df['Cloud9am'].median())
df['Cloud3pm']=df['Cloud3pm'].fillna(df['Cloud3pm'].median())
df['Temp9am']=df['Temp9am'].fillna(df['Temp9am'].median())
df['Temp3pm']=df['Temp3pm'].fillna(df['Temp3pm'].median())

In [37]:
df['Evaporation'].unique().sum()

np.float64(8798.099999999999)

In [38]:
df['RainToday'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [39]:
df['RainToday']=df['RainToday'].map({'No':0, 'Yes':1})

In [41]:
encoder=OneHotEncoder(sparse_output=False)
values=encoder.fit_transform(df[['Location','WindGustDir','WindDir9am','WindDir3pm']])

In [42]:
names = encoder.get_feature_names_out()

In [43]:
en_df = pd.DataFrame(values, columns=names,index=df.index)
df = pd.concat([df, en_df], axis=1)
df = df.drop(columns=['Location','WindGustDir','WindDir9am','WindDir3pm'])
df

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,1228089600000000,13.4,22.900000,0.6,4.8,7.625838,44.0,20.0,24.0,71.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1228176000000000,7.4,25.100000,0.0,4.8,7.625838,44.0,4.0,22.0,44.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1228262400000000,12.9,25.700000,0.0,4.8,7.625838,46.0,19.0,26.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1228348800000000,9.2,28.000000,0.0,4.8,7.625838,24.0,11.0,9.0,45.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1228435200000000,17.5,32.300000,1.0,4.8,7.625838,41.0,7.0,20.0,82.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,1498003200000000,2.8,23.400000,0.0,4.8,7.625838,31.0,13.0,11.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145456,1498089600000000,3.6,25.300000,0.0,4.8,7.625838,22.0,13.0,9.0,56.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145457,1498176000000000,5.4,26.900000,0.0,4.8,7.625838,37.0,9.0,9.0,53.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145458,1498262400000000,7.8,27.000000,0.0,4.8,7.625838,28.0,13.0,7.0,51.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145459,1498348800000000,14.9,23.229488,0.0,4.8,7.625838,39.0,17.0,17.0,62.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
x=df.drop(columns='RainToday')
y=df.RainToday

In [45]:
num_cols=x.select_dtypes(include='number').columns
cat_cols=x.select_dtypes(include='object').columns

In [46]:
over=SMOTE(sampling_strategy=0.9)
x_sam, y_sam=over.fit_resample(x,y)
y_sam.value_counts()

RainToday
0    110319
1     99287
Name: count, dtype: int64

In [47]:
under=RandomUnderSampler()
x,y=under.fit_resample(x_sam,y_sam)
y.value_counts()

RainToday
0    99287
1    99287
Name: count, dtype: int64

In [48]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [49]:
from sklearn.neighbors import KNeighborsClassifier
main_pipeline=Pipeline(
    steps=[
        ('scaler',RobustScaler()),
        ('model',KNeighborsClassifier())
    ]
)

main_pipeline.fit(xtrain,ytrain)

Pipeline(steps=[('scaler', RobustScaler()), ('model', KNeighborsClassifier())])

In [50]:
y_pred=main_pipeline.predict(xtrain)
print(classification_report(ytrain,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.89      0.93     79469
           1       0.90      0.97      0.93     79390

    accuracy                           0.93    158859
   macro avg       0.93      0.93      0.93    158859
weighted avg       0.93      0.93      0.93    158859

In [51]:
y_test=main_pipeline.predict(xtest)
print(classification_report(ytest,y_test))

              precision    recall  f1-score   support

           0       0.94      0.84      0.89     19818
           1       0.86      0.94      0.90     19897

    accuracy                           0.89     39715
   macro avg       0.90      0.89      0.89     39715
weighted avg       0.90      0.89      0.89     39715

In [52]:
main_pipeline=Pipeline(
    steps=[
        ('scaler',RobustScaler()),
        ('model',XGBClassifier())
    ]
)

main_pipeline.fit(xtrain,ytrain)

Pipeline(steps=[('scaler', RobustScaler()),
                ('model',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [53]:
y_pred=main_pipeline.predict(xtrain)
print(classification_report(ytrain,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79469
           1       1.00      1.00      1.00     79390

    accuracy                           1.00    158859
   macro avg       1.00      1.00      1.00    158859
weighted avg       1.00      1.00      1.00    158859

In [54]:
y_test=main_pipeline.predict(xtest)
print(classification_report(ytest,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19818
           1       1.00      1.00      1.00     19897

    accuracy                           1.00     39715
   macro avg       1.00      1.00      1.00     39715
weighted avg       1.00      1.00      1.00     39715

In [55]:
main_pipeline=Pipeline(
    steps=[
        ('scaler',RobustScaler()),
        ('model',LogisticRegression(max_iter=500))
    ]
)

main_pipeline.fit(xtrain,ytrain)

Pipeline(steps=[('scaler', RobustScaler()),
                ('model', LogisticRegression(max_iter=500))])

In [56]:
y_pred=main_pipeline.predict(xtrain)
print(classification_report(ytrain,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79469
           1       1.00      1.00      1.00     79390

    accuracy                           1.00    158859
   macro avg       1.00      1.00      1.00    158859
weighted avg       1.00      1.00      1.00    158859

In [57]:
y_test=main_pipeline.predict(xtest)
print(classification_report(ytest,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19818
           1       1.00      1.00      1.00     19897

    accuracy                           1.00     39715
   macro avg       1.00      1.00      1.00     39715
weighted avg       1.00      1.00      1.00     39715

In [59]:
from sklearn.tree import DecisionTreeClassifier 
main_pipeline=Pipeline(
    steps=[
        ('scaler',RobustScaler()),
        ('model',DecisionTreeClassifier())
    ]
)

main_pipeline.fit(xtrain,ytrain)

Pipeline(steps=[('scaler', RobustScaler()),
                ('model', DecisionTreeClassifier())])

In [60]:
y_pred=main_pipeline.predict(xtrain)
print(classification_report(ytrain,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79469
           1       1.00      1.00      1.00     79390

    accuracy                           1.00    158859
   macro avg       1.00      1.00      1.00    158859
weighted avg       1.00      1.00      1.00    158859

In [61]:
y_test=main_pipeline.predict(xtest)
print(classification_report(ytest,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19818
           1       1.00      1.00      1.00     19897

    accuracy                           1.00     39715
   macro avg       1.00      1.00      1.00     39715
weighted avg       1.00      1.00      1.00     39715